name: Build iOS Debug App

on: 
   workflow_call:

jobs:
  lookup-cached-build:
    runs-on: ubuntu-latest
    outputs:
      build-exists: ${{ steps.ios-debug-restore.outputs.cache-hit }}
    steps:
      - name: ğŸ› Try to restore build from cache
        id: ios-debug-restore
        uses: actions/cache/restore@v4
        with:
          path: ios-debug-build/
          key: ios-debug-build
          lookup-only: true

  build-debug-ios:
    needs: lookup-cached-build 
    if: needs.lookup-cached-build.outputs.build-exists != 'true'
    runs-on: macos-latest
    steps:
      - name: ğŸ— Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: ğŸ“¦ Install macOS dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1

      - name: ğŸ”¨ Use latest stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: ğŸ› ï¸ Build
        run: yarn build:debug:ios

      - name: ğŸ“ Prepare cache folder 
        run: |
          mkdir ios-debug-build
          mv ios/build/Build/Products/Debug-iphonesimulator/clicitestapp.app ios-debug-build/ios-debug.app

      - name: ğŸ“¡ Store built app in cache
        id: ios-debug-save
        uses: actions/cache/save@v4
        with:
          path: ios-debug-build/
          key: ios-debug-build
